### ISSUE TITLE
Build other SAC microsite pages from C6 templates

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/sac-microsite#12]

**Comment by mattdebont** [comment]
These are pages that are managed in the CMS, not related to this?

**Comment by mattdebont** [comment]
Currently have the following pages feature/data complete if not compeltely styled as of yet (on feature/refactor branch at present);

- Index (search page, drop down doesn't work yet but is populated, links off to country sites / species / habitats work) [/index.html]
- Site Lists per Country [/site/{country}.html]
- Site pages [/site/{id}.html]
  - TODO: Enlarged Maps ?
- Habitat / Species lists with site count [/habitat/index.html     /species/index.html]
- Habitats / Species Interest Feature Pages [/habitat/{id}/index.html   /species/{id}/index.html]
  - Enlarged Maps [/habitat/{id}/map.html   /species/{id}/map.html]
  - Comparison between Distribution / Site location page [/habitat/{id}/comparison.html   /species/{id}/comparison.html]
  - TODO: Distribution page, might be missing some data to produce the stats on this page, look back into existing code in user repo for Ulric to figure out what we are missing and add to species / habitat model as necessary [/habitat/{id}/distribution.html   /species/{id}/distribution.html]

**Comment by mattdebont** [comment]
Content Complete, at present, any issues with styling snags should probably be brought up seperately
