### ISSUE TITLE
Document and  handover SAC process to manager

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/sac-microsite#13]

**Comment by mattdebont** [comment]
Updated Readme.md to reflect changes to deployment, may need to investigate packaging out a .exe file as a release in some capacity

**Comment by felixMasonJncc** [comment]
Works for me

**Comment by jonparsonsjncc** [comment]
Awaiting final meeting with Kostas

**Comment by felixMasonJncc** [comment]
Demonstrated tool to kostas confirmed working on his machine
