### ISSUE TITLE
Update SAC feature pages to link to UK distribution map

### ISSUE THREAD

**Issue by ulric-wilson** [jncc/sac-microsite#18]
The link 'UK resource for this [species | habitat]' on the SAC feature pages (e.g. https://sac.jncc.gov.uk/species/S1013/ and https://sac.jncc.gov.uk/habitat/H1130/ ) points to the wrong map - it should point to the  'UK distribution map' e.g. https://sac.jncc.gov.uk/habitat/H1130/distribution  and not the SAC location map.
Please
1. update the links to the appropriate distribution map on both species and habitats pages
2. rename the link to 'UK distribution of this [species | habitat]

UW discussed with Matt when issue found 24-05-2019

**Comment by mattdebont** [comment]
Deployed a fix to live and beta, also added some whitespace below the compare map page to improve look and feel there
