### ISSUE TITLE
Add google tracking code to https://sac.jncc.gov.uk/

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/sac-microsite#19]
Below is the google analytics code to add to the sac site

[https://app.zenhub.com/files/138031480/ace3e37a-b0a2-4796-9b4b-8c8d2bfacefd/download](https://app.zenhub.com/files/138031480/ace3e37a-b0a2-4796-9b4b-8c8d2bfacefd/download)

Also below is the code for google tag manager

[https://app.zenhub.com/files/138031480/500c2849-5799-4c6c-93b4-140bb9486e57/download](https://app.zenhub.com/files/138031480/500c2849-5799-4c6c-93b4-140bb9486e57/download)

**Comment by jonparsonsjncc** [comment]
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-15841534-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-15841534-6');
</script>

**Comment by felixMasonJncc** [comment]
Google tracking code applied to sac.jncc.gov.uk.

Should work with analytics and tag manger now.

tracking code won't be deployed to beta-sac. (internal)
