### ISSUE TITLE
500 page for sac.jncc.gov.uk

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/sac-microsite#25]
for examples see pre-live.jncc.gov.uk/error-page.html
and hub.jncc.gov.uk/fail

this page needs its footer updating to be the same as the live site

also the google tag manager code needs to be added - same tag manager code that is in the current site

the text needs to be changed to:

Sorry we were unable to complete your request but our technical staff have been notified of the issue and will work to resolve it. If the problem persists please feel free to contact us.

Note: contact us needs to be a link to /contact/?ref=sac500

also could you confirm how the technical staff are going to be notified of this error

see also #57 #90

**Comment by felixMasonJncc** [comment]
500 page doesn't exist for the sac site, there is no service to fail, it's hosted on git hub. As such its not possible to configure a 500 on SAC
