### ISSUE TITLE
SAC numbers for wales incorect

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/sac-microsite#30]
See attached screen shot of problem - reported by member of public - see comment below
![sac-wales.JPG](https://images.zenhubusercontent.com/5cdad485818d2f78607e49ee/f921fe5c-f403-4956-9660-b72aa5c64572)

**Comment by jonparsonsjncc** [comment]
Dear Mary,

Many thanks for your email and alerting us to this. All good here thanks in JNCC – hope your summer is going well too!

Really sorry about the statistical error – it looks like the figure of 244 has been duplicated from the total number of SACs for Scotland.

Jon/Cathy, please can you have a look and make the correction and check if there is something wrong in any script if these summary figures are derived automatically on these webpages. Suspect it was a transcription effort though?

Thanks all,
Best
Stephen



From: Roddick,
Sent: 20 August 2019 10:10
To: Stephen 
Subject: JNCC web site minor error

Dear Stephen,
I hope this finds you well and enjoying the summer- busy though it is!
I apologise for sending this to you but was unsure who to forward this to and hoped you may be able to send on to a colleague who would be able to update.

This is to bring to your attention a minor error on the revised JNCC website that states the total number of SACs in Wales is 244. https://sac.jncc.gov.uk/site/wales

Unfortunately, we have only 95 SACs in Wales. The individual sites listed are correct, it’s only the total number at the top that needs changing. I checked the SPA and Ramsar and they are fine. 

Sorry to disturb you as I realise you’ll need to pass this on to a colleague.
With best wishes and many thanks
Mary

**Comment by felixMasonJncc** [comment]
Page now shows correct count
