### ISSUE TITLE
SAC map updates and other small changes - Felix

### ISSUE THREAD

**Issue by jonparsonsjncc** [jncc/sac-microsite#37]
Many thanks Stuart – all your help is much appreciated.

Jon – are you able to deal with replacing these on the microsite – I’m not sure what format you need?  

As mentioned previously, the map for harbour porpoise is the priority for now, and needs to be replaced fairly urgently, so if that could be replaced fairly quickly it would be much appreciated.

I’ve attached the details of what else needs doing in relation to the maps – including removal of the distribution maps. 
[https://app.zenhub.com/files/138031480/687cc6d4-5ff2-4945-b981-20d857dd8c1b/download](https://app.zenhub.com/files/138031480/687cc6d4-5ff2-4945-b981-20d857dd8c1b/download)

Please let me know if either of you need any more input or information from me.

Best wishes

Emma

From: Stuart 
Subject: FW: HP map update: SAC microsite

Hi Emma,

All species and habitat grade maps for the microsite are ready to publish. They are here: 
Z:\Prog110-FutureData\0297 Data Infrastructure\SAC Microsite\GIS - python batch mapping\images\outputGIF_SAC_species_grade
Z:\Prog110-FutureData\0297 Data Infrastructure\SAC Microsite\GIS - python batch mapping\images\outputGIF_SAC_habitat_grade

The thumbnail images are ready too:
Z:\Prog110-FutureData\0297 Data Infrastructure\SAC Microsite\GIS - python batch mapping\images\outputGIF_SAC_species_grade_thumb
Z:\Prog110-FutureData\0297 Data Infrastructure\SAC Microsite\GIS - python batch mapping\images\outputGIF_SAC_habitat_grade_thumb

All images are gifs. They can be jpeg if you prefer.

Following the checking we’ve just done, I’ve updated the wiki guidelines to include some checks that the DDE team can do without involving the Communications team. The checks include eyeballing all dots overlayed with the SAC site boundaries to spot where the dots don’t correspond with a site, and a comparison of site counts between the database and the SAC species/habitat webpages.

Stuart

**Comment by felixMasonJncc** [comment]
Updated the above on the development site.
What about the site thumbnails and uk distribution maps / map thumbs - do these need to be updated
