### ISSUE TITLE
Deployment processes

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/sac-microsite#8]

**Comment by mattdebont** [comment]
Jenkins will need to do a few things here;

 - [x] Beta Deployment => Deploy branch to beta server IIS? -> Internal-Beta
   - [x] Create IIS environment for Beta Deploy
   - [x] Define branch structure to work from
   - [x] Set up Jenkins job to build pages and deploy to IIS environment on Internal-Beta server
 - [ ] Live Deployment => 
   - [x] Deploy code to gh-pages branch for deployment
   - [ ] Delete current sac elasticsearch index - in new ticket #17
   - [ ] Push all .json search files onto import queue - in new ticket #17

**Comment by mattdebont** [comment]
Created IIS env on Internal-Beta just need to drop updated html files / other static content into d:\Websites\beta-sac

**Comment by felixMasonJncc** [comment]
Mostey working but errors if there are no page changes. Ie if git commit returns 1 and a nothing to commit message. Could either add a redundant build number file or handle this error in the groovy script.

Resolved the git credential issue when checking in to the gh-branch docs branch using info at bottom of this case:

https://issues.jenkins-ci.org/browse/JENKINS-28335
