### ISSUE TITLE
Site search index integration

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/sac-microsite#9]

**Comment by mattdebont** [comment]
Do this as part of the build process, jenkins calls a job to build list of urls / content to submit to queue

**Comment by mattdebont** [comment]
Currently have a branch (feature/search) that extracts data from habitat / species / site pages as a textual form, works off the generated html, so any other pages can be indexed if needs be, but currently only targeting those pages as they are the 'content' pages. 

Need to figure out a way to push that logic into the search queue in jenkins, current code pushes output into a .txt file is commented out for now, but will probably need to figure out a more elegant way of doing this for output to elasticsearch

**Comment by mattdebont** [comment]
Have a working output for json files on the feature/search branch, need some thought on keywords, and how to input the json from jenkins onto the queue. #15
